Add multi check-file support
`add_test_pocl()`'s `LLVM_FILECHECKS` paramater now accepts multiple
check-files. The IR-under-test will be checked against each check-file
until one of them passes. In no check-file passes, the test is failed.

Also, extend `subgroup/shuffle_small_llvm-ir-checks` to cover a new
encountered vectorization pattern (see: `sg_shuffle_small_vstore.fc`
for details).

diff --git a/tools/scripts/run-and-check-llvm-ir b/tools/scripts/run-and-check-llvm-ir
--- a/tools/scripts/run-and-check-llvm-ir
+++ b/tools/scripts/run-and-check-llvm-ir
@@ -23,7 +23,21 @@
 #
 # Usage:
 #
-# run-and-check-llvm-ir PATH/TO/llvm-FileCheck PATH/TO/llvm-dis PATH/TO/FileCheck-file PATH/TO/opencl-app ARGS
+#   run-and-check-llvm-ir FILECHECK LLVM_DIS TEST_NAME CHECK_FILE... -- CMD [CMD_ARGS...]
+#
+# Where:
+#
+# - TEST_NAME is a test name and used for test inputs and check logs.
+#
+# - FILECHECK is a path to LLVM's FileCheck tool.
+#
+# - LLVM_DIS is a path to llvm-dis tool.
+#
+# - CHECK_FILES... is one or more paths to check-files passed to FILECHECK.
+#
+# - '--' separates the CHECK_FILES... list and the CMD command
+#
+# - CMD is a test command to be run followed by its optional arguments.
 #
 # It then runs the given OpenCL application, letting it dump the final
 # vectorized work-group function in parallel.bc, which is then checked using
@@ -34,13 +48,30 @@
 
 LLVM_FILECHECK=$1
 LLVM_DIS=$2
-CHECK_FILE=$3
+TEST_NAME=$3
 shift 3
+
+CHECK_FILE_LIST=()
+while [ "$1" !=  "--" ]; do
+    CHECK_FILE_LIST+=("$1")
+    shift 1
+done
+shift 1 # consume --
+
+# Don't allow a mistake of missing out check-files turned into test pass.
+[ ${#CHECK_FILE_LIST[@]} -ne 0 ] || {
+    echo "error: no check-files given."
+    exit 2
+}
+
 APP_CMD=$@
 
 export POCL_KERNEL_CACHE=1
 export POCL_CACHE_DIR=$(mktemp -d /tmp/pocl-lit-test-XXXXXXXX)
 export POCL_LEAVE_KERNEL_COMPILER_TEMP_FILES=1
+
+# Modify the test name to be path friendly.
+TEST_NAME=${TEST_NAME////-} # replace all '/' to '-'.
 
 $APP_CMD
 RET=$?
@@ -52,25 +83,41 @@ fi
 # versions first) so we can inspect the specialized WG(s) as well as the
 # generic one in known positions in the output.
 BC_FILES=$(find $POCL_CACHE_DIR -name parallel.bc|sort -r)
-LL_FILE=$POCL_CACHE_DIR/parallel-bcs-to-filecheck.ll
+FILE_CHECK_INPUT=${PWD}/${TEST_NAME}-ir-check-input.ll
 
+> $FILE_CHECK_INPUT
 for BC_FILE in $BC_FILES
 do
-   echo "; $BC_FILE" >> $LL_FILE
-   $LLVM_DIS $BC_FILE -o - >> $LL_FILE
+   echo "; $BC_FILE" >> $FILE_CHECK_INPUT
+   $LLVM_DIS $BC_FILE -o - >> $FILE_CHECK_INPUT
 done
 
-cat $LL_FILE | $LLVM_FILECHECK $CHECK_FILE
-RET=$?
+CHECK_OUTPUT_LIST=()
+for CHECK_FILE in ${CHECK_FILE_LIST[@]}; do
+    CHECK_FILE_BASENAME=$(basename $CHECK_FILE)
+    CHECK_OUTPUT=${PWD}/${TEST_NAME}-${CHECK_FILE_BASENAME}.log
+
+    echo "; check-file: '$CHECK_FILE'" > $CHECK_OUTPUT
+    $LLVM_FILECHECK --input-file=$FILE_CHECK_INPUT $CHECK_FILE >>$CHECK_OUTPUT 2>&1
+    RET=$?
+    [ $RET -eq 0 ] && break;
+
+    CHECK_OUTPUT_LIST+=(${CHECK_OUTPUT})
+done
 
 trap 'rm -fr $POCL_CACHE_DIR' EXIT
 
 if test $RET -eq 0;
 then
-    echo LLVM IR checks OK.
+    echo "LLVM IR checks OK."
     exit 0
 else
-    cat $LL_FILE
-    echo LLVM IR checks FAIL.
+    echo "FAIL: none of the check-files passed!"
+    cat $FILE_CHECK_INPUT
+    echo "note: IR used in file-checks: $FILE_CHECK_INPUT"
+    echo "note: file-check logs are written in:"
+    for CHECK_OUTPUT in ${CHECK_OUTPUT_LIST[@]}; do
+	echo "  ${CHECK_OUTPUT}"
+    done
     exit 1
 fi
